### ISSUE TITLE
No products in demo

### ISSUE THREAD

**Issue by ardouglass** [swiftype/swiftype-faceted-search-example#1]
It looks like this demo is broken, unless I have to manually add products to work.

I get an error in the console which may help debug.

``` javascript
/**/jQuery17108199375857832734_1464031971891({"record_count":0,"records":{"products":[]},"info":{"products":{"query":"hey yo add produ","current_page":1,"num_pages":0,"per_page":10,"total_result_count":0}},"errors":{}})
```

**Comment by tehsven** [comment]
Hi @ardouglass, there are products in the example. Type `Prod` and you should see autocomplete options. Type `Product` in the search box and press `Enter` to see results.
